### ISSUE TITLE
How to use Barba.js with several scripts

### ISSUE THREAD

**Issue by Tannate** [barbajs/barba#317]
Hello,

I'm sorry about this question, but I'm not sure if I well understand how to use Barba.js.
This is (more or less) the structure of my website and where I put the Barba code :

It doesn't work well... My scripts js are not well executed for each page.

### header.php
```
<html>

<link href="styles.css">
<script src="myscripts.js"></script>

  <div id="barba-wrapper">
    <div class="barba-container" >

      my html code here 

    </div>
  </div>

</html>
```

### index.php
```
<html>
 
 <div id="barba-wrapper">
    <div class="barba-container" >

      my html code here 

    </div>
  </div>

<script> 
jQuery(document).ready(function($) {
    Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container) {

        my scripts code here (with php, this why I can't put it in my "myscripts.js")

    });
    Barba.Pjax.start();
});
</script>

</html>
```

### single.php
```
<html>

  <div id="barba-wrapper">
    <div class="barba-container" >
      my html code here 
    </div>
  </div>

<script> 
jQuery(document).ready(function($) {
    Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container) {

        my scripts code here (with php, this why I can't put it in my "myscripts.js")

    });
    Barba.Pjax.start();
});
</script>

</html>
```
### myscripts.js
```
jQuery(document).ready(function($) {
    Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container) {

        my scripts code here 

    });
    Barba.Pjax.start();
});
```
### styles.css
```
 my styles code here 
```
Thank you for your precious help.

**Comment by jhabdas** [comment]
@Tannate Given the use of PHP and jQuery chances are you're attempting to modify a WordPress theme. Am I right? If that's the case, your first stop should be with the theme developer. Otherwise, you please consider working on your understanding of [`document.readyState`](https://devdocs.io/dom/document/readystate) before you attempt to resolve the issue. Last thing, if you want more control over the loading of your scripts you could consider using fetch injection.

**Comment by jhabdas** [comment]
@Tannate Given the use of PHP and jQuery chances are you're attempting to modify a WordPress theme. Am I right? If that's the case, your first stop should be with the theme developer.

Otherwise please consider working on your understanding of document.readyState before you attempt to resolve the issue. Last thing, if you want more control over the loading of your scripts you could consider using fetch injection.

**Comment by jhabdas** [comment]
@Tannate Given the use of PHP and jQuery chances are you're attempting to modify a WordPress theme. Am I right? If that's the case, your first stop should be with the theme developer.

Otherwise, consider working on your understanding of [`document.readyState`](https://devdocs.io/dom/document/readystate) before you go too far down the rabbit hole. You may have some luck using [`fetch-inject`](https://git.habd.as/jhabdas/fetch-inject) to gain more control over the ordering of your scripts (i.e. and remove that blocking external script in your `head`.

**Comment by aswinkumar863** [comment]
Hello @Tannate ,
newPageReady event need not be added to each page. The structure should be like this.

### header.php

outside barba-wrapper
```
<link href="styles.css">
<script src="barba.min.js" type="text/javascript"></script>
<script src="myscripts.js" type="text/javascript"></script>
```

barba-wrapper inside body
```
<body>
    ...

    <div id="barba-wrapper">
        <div class="barba-container" >

            ...Put here the content you wish to change between pages...

        </div>
    </div>

    ...
</body>
```

### index.php and single.php

outside barba-wrapper
```
<link href="styles.css">
<script src="barba.min.js" type="text/javascript"></script>
<script src="myscripts.js" type="text/javascript"></script>
```

barba-wrapper inside body
```
<body>
    ...

    <div id="barba-wrapper">
        <div class="barba-container" >

            ...new content...

        </div>
    </div>

    ...
</body>
```

### myscripts.js

```
jQuery(document).ready(function($) {
    Barba.Pjax.start();
});
```

**Note**: Your index.php and single.php can also return barba-wrapper only (without html and body). For more [http://barbajs.org/partial-output.html](url)

**Comment by thierrymichel** [comment]
Please, feel free to reopen if you still having problems…
