### ISSUE TITLE
Click link go to new page and refresh page and go back animation not working

### ISSUE THREAD

**Issue by abhishekaugust84** [barbajs/barba#320]
Hello,

Thanks for the great library,
I am facing issue using Barba.
I have 2 different animations for about us page and team detail page

When I load home page and click on about us page animation works, after that when I refresh about us page and press browser back button animation doesn't work. 
Same with Team detail page also.

How to set 2 different animation effects on browser back button for about and team detail page when browser get refresh and press browser back button?

**Comment by gfnool** [comment]
It's a bit tricky because it involves replacing history state, but it could be done in this way.
I've tested it quickly so I'm not sure it's bulletproof and if there is a better way.

`
// save current status in history, even the first time
Barba.Dispatcher.on('transitionCompleted', function(currentStatus, prevStatus) {
  history.replaceState(currentStatus, null, currentStatus.url);
});

// this is just a basic transition to return in Barba.Pjax.getTransition
var HideShowTransition = Barba.BaseTransition.extend({
  start: function() {
    this.newContainerLoading.then(this.finish.bind(this));
  },
  finish: function() {
    this.done();
  }
});

// check if a history.state exists and look for a namespace (you have to put data-namespace on .barba-container)
Barba.Pjax.getTransition = function() {
	var destination = history.state ? history.state.namespace : 'unknown';
	console.log("destination is " + destination);
	// add custom logic based on destination namespace
	return HideShowTransition;
};

Barba.Pjax.start();`

**Comment by thierrymichel** [comment]
Please, feel free to reopen if you still having problems…
