### ISSUE TITLE
Can I use Barba on Angular Routes? How?

### ISSUE THREAD

**Issue by ntoni** [barbajs/barba#338]
Can I setup the routes to make Barbajs work? With Angular JS standard Routes settings, the page is reloaded without transition. How it works?

**Comment by luruke** [comment]
Hello @ntoni , I never tried to use barba together with a SPA framework/routing solution.
I'm sure those routers/framework already provide solution to create transitions between page.

Is there any specific reason you wanted to use barba with it?

**Comment by Frontend007** [comment]
I am trying to implement barba js in angular but can't, is there any suggestion?

**Comment by xavierfoucrier** [comment]
Hello @Frontend007 🕶️ 

This question is quite old, and was asked under BarbaJS v1.

Unfortunately, the answer the same today.
From the last FAQ documentation [here](https://barba.js.org/faq/#Can-I-use-Barba-inside-a-React-Vue-Next-app):
> When using a front-end framework like React, Vue or Next, you should take a look at the framework documentation and use everything the framework is bringing you, like page transitions, routes, etc. instead of trying to implement another library over a complex framework layout.

Since there are many features implemented today in those frameworks, we won't push more efforts to write custom examples/documentation in order to cover all use cases. Hope you can understand.

Have a nice day and thanks for coding with BarbaJS 🎉
