### ISSUE TITLE
Change layout of page

### ISSUE THREAD

**Issue by alexey13** [barbajs/barba#347]
Good day! Barba is awesome. Thanks Luke!
I have different layouts of a page and would like to change barba container position in dom. What is the best way? My thoughts: if clicked on the link of the page that has a different layout, change barba container position on the current page and after load page with a different layout.
Examples of layouts:

```
<div id="page">
<div id="barba-wrapper">
	<div class="barba-container" data-namespace="">
		<header id="masthead" class="site-header"></header>
		<div id="content" class="site-content">
			<div id="primary" class="content-area">
				<main id="main" class="site-main"></main>
			</div>
		</div>
	</div>
</div>
</div>
```
```
<div id="page">
<div id="content" class="site-content {{class}}">
	<div id="primary" class="content-area">
		<div class="row">
			<div class="col-md-9 order-md-2">
				<main id="main" class="site-main">
					<div id="barba-wrapper">
						<div class="barba-container"></div>
					</div>
				</main>
			</div>
			<div class="col-md-3 order-md-1">
				<aside class="widget-area"></aside>
			</div>
		</div>
	</div>
</div>
</div>
```

**Comment by gfnool** [comment]
Hi @alexey13,
Barba, by design, works only in its "barba wrapper" and change the "barba containers" in it.
So there is no way to change the outside DOM like you want to do.

Anyway, there are some tricky ways you can do that (changing every time the outside DOM of the wrapper, listening to events like newPageReady) but in my opinion it's a weird approach and I'm not suggesting you to do it.

It's better to refactor the DOM structure of the pages according to the Barba specs.

**Comment by alexey13** [comment]
Thank you @gfnool ! Yes, I made a refactor of DOM. Agree that it's bad solution to change wrapper in dom

**Comment by thierrymichel** [comment]
:+1:
