### ISSUE TITLE
Changing URL window.location.hash triggers page transition.

### ISSUE THREAD

**Issue by khaiknievel** [barbajs/barba#359]
Im trying to change the url location with a hash, e.g #title.
```js
 window.location.hash = '#title' 
```
**Expected Behaviour**
To have it scroll to the ```#title.offsetTop```, 

**Actual Behaviour**
But it seem to trigger the popstate and thus, trigger the transition.

Is there a barba specific event that i can listen to and decide whether to proceed or prevent the transition?

Barba version 2.1

**Comment by thierrymichel** [comment]
This echoes to recurrent discussions about how to manage anchors and links to "self" page.
I've worked on a POC allowing user to define "self" transitions (`{ name: 'self' }`).
It works quite well.
If none, it reloads the page on same url and scrolls to anchor.
If defined, users can manage "something" based on `next.url.hash`, for example…
Downside: you can only have 1 "self" transition.

Another solution is to add a new `self` hook so users will be able to add `self() {}` to any transition.
Not tested. I dread possibly duplicate code if some global behavior is wanted.
But maybe this can be avoided using global hook (`barba.hooks.self()`).

Any thoughts?

Ping @luruke, @xavierfoucrier, @evfleet…

**Comment by xavierfoucrier** [comment]
Since I had opened a similar issue during the development process, I think using a `self` transition or a global `barba.hooks.self` for self targeted links should do the job.

In barba v1, I had to prevent the transition on self targeted links, but I didn't manage any anchor links using barba for now...

```js
// prevents the user to reload the page if the location is the same
if (this.href === window.location.href) {
  e.preventDefault();

  // do nothing if the user is already at the top of the page
  if (window.scrollY === 0) {
    return;
  }

  // automatically scrolls to the top of the page on same location
  window.scroll({
    top: 0,
    left: 0,
    behavior: 'smooth'
  });
}
```

Regarding anchor links from another point of view, since they are typically made to focus a section in a page, barba should use a transition first to redirect the user to the specified page, *then*, call the appropriate hook to allow scrolling to the specified section.

**Comment by thierrymichel** [comment]
@khaiknievel latest release (`2.1.1-next.87`) should fix it.
Would be nice if you can test  on your side and confirm everything is fine…

Expected when triggering on same URL (click or popstate):
- default: reload the page
- with anchor link: scroll to (same for `location.hash`)

---

I will keep this open because I've added a new behavior which allows to use a "self" transition (`{ name: 'self' }`);
If present, it will be used for the "same URL" scenario (with or without anchors).
It is a rough implementation and I would like to have some feedback before going further (adding `self` hook, for example…).

**Comment by xavierfoucrier** [comment]
Hi @thierrymichel !

I will test that as soon as possible next week and give a feedback :sunglasses:

**Comment by khaiknievel** [comment]
@thierrymichel Thanks. Using latest release (```2.1.1-next.87```).

Expected when triggering on same URL (click or popstate):

- [x] default: reload the page
- [x] with anchor link: scroll to (same for location.hash)

---

All is 👍.

**Comment by khaiknievel** [comment]
@thierrymichel Seems like this update introduce another issue though. Navigating back does not trigger any transition. 

```2.1.1-next.87```

**Comment by thierrymichel** [comment]
@khaiknievel good catch! Thanks 🙏
Fix is on his way…
