### ISSUE TITLE
Barba container always load at the end of wrapper

### ISSUE THREAD

**Issue by antoine1000** [barbajs/barba#409]
## The problem

When switching pages, my footer loads on top of the container instead of staying at the bottom of the page. The `<main data-barba="container">` loads after the footer instead of just updating the content.

I would like to put my header and footer inside the `wrapper` but not inside the container, as they do not need to be updated when a new page loads.

Guess it is related to this issue : #289

### Expected behaviour

The footer should stay after the `<main data-barba="container">` section, at the bottom of the page.

### Actual behaviour

The `<main data-barba="container">` moves after my footer element.

### Code To Reproduce Issue

```html
<head>...</head>

<body data-barba="wrapper">
 <!-- the header is placed inside the wrapper but outside the container -->
 <header>
  <nav>
   <a href="/">Homepage</a>
   <a href="/products">Products</a>
  </nav>
 </header>

<main data-barba="container">
  ... content...
</main>
 
 <!-- the footer is placed inside the wrapper but outside the container -->
 <footer>
  ...
 </footer>
</body>
```

### See the video

![barba-footer-bug](https://user-images.githubusercontent.com/18557215/59684568-93cb8f00-91da-11e9-9a52-24d1be1fb756.gif)

---

## Environment

- Barba version that exhibits the issue: **2.3.10 (@barba-core)**
- Browser OS/version used: **Chrome 74.0**

**Comment by c0mrx** [comment]
This is because you have the `body` set as your wrapper. Wrap a div around `main` and make that your wrapper instead. Barba appends the `container` to the `wrapper`, so it will always end up at the bottom, so if you have more elements in there they will be bumped up.

**Comment by antoine1000** [comment]
That was it,  thanks for your quick and accurate answer. It works as expected now. I'm closing the issue.

**Comment by dangelion** [comment]
As said @luruke [here](https://github.com/barbajs/barba/issues/289#issuecomment-429770921) the `wrapper` should just contain the `container`.

I'd suggest to make this more clear in the [docs](https://barba.js.org/docs/v2/user/core.html) in this point:

```
<body data-barba="wrapper">
  <main data-barba="container" data-barba-namespace="home">
    <!-- put here the content you wish to change between your pages -->
  </main>
</body>
```

**Comment by xavierfoucrier** [comment]
@dangelion the `wrapper` can contain other elements around the `container`.
I will update the documentation accordingly.

Thanks for your feedback :wink:

**Comment by sheriffderek** [comment]
I'm running into this situation as well.

The docs currently explain to do exactly what the OP did with their code.

https://barba.js.org/docs/getstarted/markup

![CleanShot 2022-11-15 at 09 14 11@2x](https://user-images.githubusercontent.com/2066617/201983739-bb8f31df-2df6-4f4c-9e8a-4c4af0610348.png)

I was assuming that the wrapper needed to be around the other content as well to help make menu style updates and things like that.

Is it the case that it should _not_ be written like that? I'm looking at v2.9.7 docs

<img width="396" alt="CleanShot 2022-11-15 at 09 19 26@2x" src="https://user-images.githubusercontent.com/2066617/201984748-26b78ee5-89e9-4045-a782-7af01ccfbc39.png">

As suggested here, this markup does the trick. And I had tried many different combinations over the last few days - but based on the docs - I would have never tried this combo - because it says specifically to put the header and footer out there.
