### ISSUE TITLE
How to add and remove scripts in certain pages

### ISSUE THREAD

**Issue by ProdesignerAgency** [barbajs/barba#430]
Hello, 
I have a problem with adding and removing scripts on some pages. I suspect this has to do with data-barba-namespace but these scripts are outside of data-barba = "container".
I have no idea how to add them if I am on the right page or delete them if I am off this page.

Ps. it's not about functions, but about files e.g.

`<body>
<div data-barba = "container">
<div data-barba-namespace="somescripttload">
</div>
</div>
<script src = "somescript.js">
</body>`

Best!
Ps. I love Barba!

**Comment by xavierfoucrier** [comment]
Hi @ProdesignerAgency,

For now, as specified in the documentation:

> _Be aware, everything inside of this wrapper and outside of the container **will not be updated** by Barba_

Meaning it would not be updated as well, because the page is not fully reload when using barba.

So, if you want to add scripts on some pages, you will need to use barba `View` to target the right page and **manipulate the DOM** to create the `<script>` tags and load your scripts.

Note that in a near future, barba will be able to update the `<head>`, depending on the view you are entering/leaving/etc.., with the `@barba/head` module. :+1:

**Comment by ProdesignerAgency** [comment]
OK thank You :)

> So, if you want to add scripts on some pages, you will need to use barba View to target the right page and manipulate the DOM to create the <script> tags and load your scripts.

Can You show me a little example how to do this?

Btw i'm waiting for the near future 💃

**Comment by xavierfoucrier** [comment]
@ProdesignerAgency sure!

```js
// init barba library
barba.init({
  views: [{
    namespace: 'contact',
    beforeEnter({ next }) {
      
      // load your script
      let script = document.createElement('script');
      script.src = 'https://localhost:8080/awesome-site/script.js';
      next.container.appendChild(script);
    }
  }]
});
```

This will create a `<script>` element **at the bottom of the `next` container** every time you will enter the `contact` page. As the container is removed when leaving the page, your script will be removed too... then added again when entering the page.

If you need help on `View`, please read the documentation: https://barba.js.org/docs/v2/user/core.html#view-object.

> Note that loading scripts like this depends on your needs

**Comment by saket-wdev** [comment]
> This will create a `<script>` element **at the bottom of the `next` container** every time you will enter the `contact` page. As the container is removed when leaving the page, your script will be removed too... then added again when entering the page.

Hi, can you please help me?

Even though, the JS file gets removed from the DOM when we leave one page and go to the other. But I am still able to use the code from the previous JS file which I dont want to use because it is creating conflicting results in pages.

**Comment by xavierfoucrier** [comment]
Hi @saket-wdev,

If the previous code is not needed anymore in the next page, you should take a look at `View` instead.
See https://barba.js.org/docs/advanced/views/.

If you need more help for implementing stuff inside your code, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

:wink:
