### ISSUE TITLE
Errors are not reported from hooks

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [barbajs/barba#447]
When some dodgy code is inside a Views `beforeLeave()` function for example, the console doesnt show an error, instead the URL changes, but the page doesnt update

Im using Chrome 77, MacOS 10.14.3

I created a minimal reproduction repo here: https://github.com/matthewjumpsoffbuildings/barba-issue

Chuck it in a local dev environment like valet and browse to the index html, click the About link. If you look in `src/app.js` you'll see the views have a call to a non-existent function `SOME_BROKEN_STUFF()`, but no console error appears, the URL updates, but the DOM doesnt change.

**Comment by xavierfoucrier** [comment]
Hi @matthewjumpsoffbuildings,

Sorry for the late reply, I will dig into that next week and give a feedback :wink:

**Comment by xavierfoucrier** [comment]
Hi @matthewjumpsoffbuildings,

This is probably because it's **Promise based when hooks are chained and triggered**, a simple Promise `catch` should do the trick.
> https://github.com/barbajs/barba/blob/master/packages/core/src/hooks.ts#L113

After cloning your repo, it appear that no error are thrown since the `debug` mode is not properly set to `true` with the appropriate `logLevel`:

```js
barba.init({
  debug: true,
  logLevel: 'error',
  views: ...
});
```
> https://barba.js.org/docs/v2/user/core.html#debug

Finally, you can also do a **simple try/catch**, but yeah, errors should appear by them self...

I will mark this as bug and wait for @thierrymichel opinion.
Thanks again for the catch :wink:

**Comment by xavierfoucrier** [comment]
Hi @matthewjumpsoffbuildings,

This is probably because it's **Promise based when hooks are chained and triggered**, a simple Promise `catch` should do the trick.
> https://github.com/barbajs/barba/blob/master/packages/core/src/hooks.ts#L113

After cloning your repo, it appear that no error are thrown since the `debug` mode is not properly set to `true` with the appropriate `logLevel`:

```js
barba.init({
  debug: true,
  logLevel: 'error',
  views: ...
});
```
> https://barba.js.org/docs/v2/user/core.html#debug

Finally, you can also do a **simple try/catch**, but yeah, errors should appear by them self...

I will mark this as bug and wait for @thierrymichel opinion.
Thanks again for the catch :wink:

**Comment by matthewjumpsoffbuildings** [comment]
I see this is closed, has this been resolved, or is it just being closed to keep the issues tidy?
