### ISSUE TITLE
Prefetch combined with true cacheIgnore is looping on prefetching

### ISSUE THREAD

**Issue by Liroo** [barbajs/barba#486]
## The problem

What I try to do is to preFetch page before the user click on the link. As it is a dynamic website, I don't want to keep the page in cache.

Actually, it doesn't happen every time so I suspect the Observer or the current implementation that does not handle this case.

When I hover a link, every time I move my mouse (on `mousemove`), the link is re-pre-fetch.

### Expected behavior

I think the best behavior should that the link is pre-fetch for the current page. And when a page transition is triggered, the cache goes empty.

### Actual behavior

Don't really know what is the actual behavior on the end but the link is pre-fetch too many times.

### Code To Reproduce Issue [ Good To Have ]

```js
    barba.use(barbaPrefetch);

    barba.init({
        timeout: 5000,
        // debug: true,
        cacheIgnore: true,
        sync: true,
        transitions: [],
    });
```

---

## Environment

- Barba version that exhibits the issue: every

**Comment by xavierfoucrier** [comment]
Hi @Liroo,

Thanks for opening the issue!

First of all, you need to distinguish the `@barba/core` prefetch behavior and the `@barba/prefetch` module:
- `@barba/core` prefetch all eligible links **on mouseover**, you can disable this feature by using the `prefetchIgnore` property, see https://barba.js.org/docs/v2/user/core.html#prefetchignore
- `@barba/prefetch` module prefetch all eligible links that **enter the viewport**: that mean that it won't prefetch links that you can't see on screen, see https://barba.js.org/docs/v2/user/prefetch.html

Anyway, you have highlighted another issue that happen when the cache is disabled and the `@barba/core` prefetch option is enabled. Indeed, it doesn't make sense to reload the same page several times in succession for the same view, even if it make sense to clear/ignore the cache for the same page when you set `cacheIgnore` to `true`.

Your expected behavior should be the default one.
I will mark this as bug. Thanks again :wink:

**Comment by xavierfoucrier** [comment]
We have decided with Thierry to not fix this behavior, as `cacheIgnore: true` and `@barba/prefetch` plugin shouldn't be used together.
