### ISSUE TITLE
New barba website + v2 

### ISSUE THREAD

**Issue by Jaune8** [barbajs/barba#488]
Hi, 
I see that's you have realeased the new barba website witch is beautifull and works perfectly with transitions and animations, and i would like to do the same <3
I used v1 and i'm not an expert, i used HTML page example and i test if an wordpress website in local XAMPP, but in v2 i didn't see examples, it will be usefull to download simple HTML transitions with basic HTML and JS and implement in my website  :)

Examples in Codepen are broken :/ 
Thanks a lot for all your work !
Love barba.js ! :) <3

**Comment by kojimajunya** [comment]
Can't see documents...
https://barba.js.org/docs/v2/user/core.html

**Comment by Jaune8** [comment]
Cool thanks, examples works :) , but i think i will wait for the preset of animation to be released

**Comment by olets** [comment]
> Examples in Codepen are broken :/

Were they broken or were you tripped up by #497?

**Comment by xavierfoucrier** [comment]
Hi @Jaune8,

[Since one month](https://twitter.com/barba_js/status/1225369729117958145), official documentation is hosted on https://barba.js.org.
Future examples will be added to the **Barba website** right here: https://barba.js.org/examples

As far as I know, Codepen example works well.

@kojimajunya this is an old documentation link: they have been replaced when the site were released

> **Announced on Slack**:
> For thoose who are not comfortable with the current documentation, I let you know that we will work on a second version soon: with a better structuration and simpler/clearer code+examples.

Thanks for using Barba :wink: 
I am closing the issue.
