### ISSUE TITLE
Prefetch only an element

### ISSUE THREAD

**Issue by theamnesic** [barbajs/barba#489]
Hi!

An enhancement idea for `@barba/prefetch`.

As [quicklink](https://github.com/GoogleChromeLabs/quicklink#set-the-dom-element-to-observe-for-in-viewport-links), it could be awesome if we can set the element to observe.

And by default, `document`.

— G

**Comment by xavierfoucrier** [comment]
Hi @theamnesic,
Very good idea :+1:

**Comment by psntr** [comment]
This would be indeed pretty useful, I'm adding also here a question, regarding prefetch. Is it currently possible to decide what to prefetch? By default it prefetch the link and return a XHR response. 

I'm trying to prefetch a JSON instead of a XHR response. But my href value is a default link, I don't want to change the value to the JSON link in order to keep the link available in case javascript is disabled. Maybe an option in data-attribute?

**Comment by xavierfoucrier** [comment]
Hello everyone 👋 

@psntr Sorry for late reply 😁 ... I just wanted to let you know that currently, there is no plan to support custom mime type to prefetch with this plugin, since you can do it with regular javascript.

@theamnesic Same, sorry for late reply on this thread. I just noticed that there is a lake in the Barba documentation for the `@barba/prefetch` plugin, I will update it on next release. You can already **prefetch only a specific area of your page** with:

```js
barba.use(prefetch, {
  root: document.querySelector('.area-to-prefetch')
});
```
> By default, `document.body` is used.
