### ISSUE TITLE
Force transition instead of reload page (clicking on a rendered map)

### ISSUE THREAD

**Issue by dangelion** [barbajs/barba#501]
Hi
I'm using [this library](https://cssmapsplugin.com/settings/) to render a clickable map, like this https://cssmapsplugin.com/get/belgium/. 
So then clicking on a region of the map it navigates to the page of that region.

I'm initializing the library `$("#map").CSSMap()` inside the hook `barba.hooks.beforeEnter()`, it's ok, but when I click a region it reloads the page instead of start the transition.

I precise that Barba works well for all the other pages, triggered by "standard" links. There's just a problem between that library and barba.

I don't get where am I wrong. Have you idea of how to handle this thing?
Thanks in advance

**Comment by xavierfoucrier** [comment]
Hi @dangelion,

Sorry for the late reply (again ^^),

I think it doesn't work because, probably, jQuery is building the map links on the fly... making them **hard to be detect by Barba** :smiley:

Have you tried to init the map on the `afterEnter`, or `after` hook?

If it doesn't work, you will probably need to **bind each map links** by using `preventDefault` and `barba.go('page.html');` to properly call the barba transition.

Give us a feedback.
Thanks! :+1:

**Comment by dangelion** [comment]
Hi @xavierfoucrier 
I also think it. Already tried to init the map on the afterEnter or after hook, but doesn't work.
Your second solution would be something like this (just a raw code to understand)?

```
$(document).on("click", "div.region-1", function(e){
  e.preventDefault();
  barba.go('region-1.html');
});
```

To do for each region. Right?

**Comment by xavierfoucrier** [comment]
@dangelion yes!

That's what I was thinking about, and if there is a transition available to go to `region-1.html`, Barba will play it :wink: 

Thinking about another thing, have you try to init the map first, then when the map is fully loaded (with links availables) to init Barba? This way links should be "parsed" by Barba... let's try.
