### ISSUE TITLE
PrestaShop implementation

### ISSUE THREAD

**Issue by dangelion** [barbajs/barba#505]
Hi
we're building a custom theme for PrestaShop and we'd love to add Barba for page transitions.
Anyone has already tried it with PrestaShop? Are there some complexities?
Any advices are welcome. 
Thanks

**Comment by dangelion** [comment]
Hi @xavierfoucrier 
yes I'm agreed with you. Here is a Prestashop demo: https://demoprestashop.prestarocket.com/
Inspecting the code are you able to figure out if it could works?
I see a different count of <script>s on the various template pages but I see a common "bottom-e2e02b24.js"
Thanks

**Comment by xavierfoucrier** [comment]
Hi @dangelion,

Thanks for the feedback, in fact you should try to enable Barba and see if everything works well, this is the only way to check :wink:

You should try to put `data-barba="wrapper"` on the `<body>` and `data-barba="container"` on the `<main>`. But I see that classes are append to the body between the home and product page, this can cause issues on the main stylesheet... but give a try and see what's happen! :rocket: 

> As WooCommerce is running under WordPress, and Barba is well compatible with WordPress websites, this may probably works too.

**Comment by dangelion** [comment]
@xavierfoucrier Yes, next I'll try on this project. For updating the <body> classes I thought to use this code https://github.com/barbajs/barba/issues/51#issuecomment-531465899 that works well on Wordpress. Should it works...

**Comment by xavierfoucrier** [comment]
Fine, let's give a try and a feedback here.
Feel free to close the issue :wink:

**Comment by ejazrasool** [comment]
Hi, just chiming in here. Since the question is about using this library with a complex ready-made software, would you like to comment on what type of applications barba.js easiest to integrate into? list of scenarios where barba.js works best and scenarios that are not suitable for using this library?

I'm also planning on using barba.js with <insert some complex CMS/Shopping cart> here but it looks like an enormous task since of course it 

- adds classes to body tag
- highlights current nav links
- changes a nav link or two based on special circumstances
- shows a new small menu in nav area for logged in users
- loads different javascript files based on current area the user is visiting

to list some of the caveats.
