### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by xavierfoucrier** [barbajs/barba#509]
For those who are not comfortable with the current documentation, we are working on a second version with a **better structuration and simpler/clearer code+examples**.

Roadmap:
- [x] new navigation tree
- [x] write / review `getstarted` section
- [x] write / review `advanced` section
- [x] write / review `plugins` section
- [x] fix css stuff (header clickable zone, links highlight, nav, ..)
- [x] fix typography rendering for `code` blocks
- [x] fix some website typos
- [x] update dependencies
- [x] add `locomotive-scroll` in third party scripts
- [x] add `recaptcha` in third party scripts
- [x] add / review codepens (fix typo, add based on third party scripts)

> We know that everyone is not comfortable with **ES6/import/webpack/build** stuff, and a lot of you are using Barba through the CDN file: that's why we have acting to update the documentation and improve the way users are getting started when using Barba

**Comment by Jonatan-r** [comment]
On https://barba.js.org/docs/plugins/css/ it's shown to do this:

```
barba.use(css);
barba.init();
```

But.. that gives me this `ReferenceError: Can't find variable: css ` and.. Barba.js does not run. But, if write it in this order:

```
barba.init();
barba.use(css);
```

– barba runs.

(I'm using a CDN: `<script src="https://unpkg.com/@barba/core"></script><script src="https://unpkg.com/@barba/css"></script>`)

**Comment by Jonatan-r** [comment]
Also, if I change barba.use(css); to barba.use(barbaCss); I don't get `ReferenceError: Can't find variable: css`

**Comment by Jonatan-r** [comment]
So.. I figured it out.

If I follow this https://barba.js.org/docs/plugins/css/#Custom-rule :

```
  barba.use(barbaCss);
  barba.init({
  transitions: [{
    name: 'fade',
    leave() {},
    enter() {}
  }]
});
```

and I follow I also copy the css from https://barba.js.org/docs/plugins/css/#Custom-rule CSS:

```
.fade-leave-active,
.fade-enter-active,
.slide-leave-active,
.slide-enter-active {
  transition: opacity 450ms ease, transform 650ms ease-in-out;
}

.fade-leave,
.fade-enter-to {
  opacity: 1;
}

.fade-enter,
.fade-leave-to {
  opacity: 0;
}
```

it works!... Yay.. My simple basic CSS page fade transition. Horrayy... But.. It was, following the docs, _**not**_ logic getting there.. Why? Well because I just initially followed it from the top down:

That is I just thought it was plug'n'play using the first paragraphs code,  totally copy-pastable:
https://barba.js.org/docs/plugins/css/#How-it-works

```
    barba.use(barbaCss);
  barba.init({
 
});
```

And CSS:

```
.barba-leave-active,
.barba-enter-active {
  transition: opacity 450ms ease;
}

.barba-leave,
.barba-enter-to {
  opacity: 1;
}

.barba-enter,
.barba-leave-to {
  opacity: 0;
}
```

But.. no. It is **_not_** obviously clear, as a noob following the docs, just wanting some of the very very simplest CSS totally basic fade from page to page transition you can not just do the justabovementioned initial https://barba.js.org/docs/plugins/css/#How-it-works. But you have to figure out that you need to actually follow this part: https://barba.js.org/docs/plugins/css/#Custom-rule

– That is, that you need   :
```
barba.init({
  transitions: [{
    name: 'xxxx',
    leave() {},
    enter() {}
  }]
});
```

– to actually make it work :)

**Comment by Jonatan-r** [comment]
Oh and also, for basic page to page fade transitions, you might wanna point out in the docs if it's actually any more or less efficient (performance wise) using @barba/css css transitions instead of GSAP? 😄
