### ISSUE TITLE
Request: Sample code/codepens to integrate Google recaptcha V3

### ISSUE THREAD

**Issue by lasagner** [barbajs/barba#516]
Hello, thank you to make Barba available for everyone!
I would like to integrate Google recaptcha V3 inside only one page.
I'm using "views" but still doesn't show the recaptcha unless I refresh the current page.
Could you post here a correct example?

Thank you in advance!!

**Comment by xavierfoucrier** [comment]
Hi @lasagner,

It's a duplicate issue of https://github.com/barbajs/barba/issues/399.

For now, **we don't have a third party code snippet or specific implementation directives** for ReCaptcha v3, but I can't add it to the pipe in order to have it on the documentation website.

It should work like any other third party scripts:
- `import` inside your bundle or `<script>` inside your head/page bottom
- call `grecaptcha.execute(...)` inside the appropriate [hook](https://barba.js.org/docs/advanced/hooks/)

> See ReCaptcha official documentation if needed: https://developers.google.com/recaptcha/docs/v3

**Comment by xavierfoucrier** [comment]
Hi everyone,

I just add a [dedicated Google ReCaptcha section](https://barba.js.org/docs/advanced/third-party/#Google-ReCaptcha) inside the **advanced third party scripts** documentation on the Barba website.

> This section may evolve in time based on Google ReCaptcha updates...

Happy reading! :wink:
Closing the issue.

**Comment by lasagner** [comment]
Thank you so much guys!! 🙏 You are the best ❤️

**Comment by jeronimus23** [comment]
@xavierfoucrier Thank you very much for this, I needed it too but I have a doubt. In the script for the ReCaptcha you have to send the token to the server to verify it but I have no idea how to do this. I already checked the google documentation but there is no concrete example, could you share an example, I don't know how to apply this to my site. I see the google badge in my site and my form is arriving correctly but I don't know if the captcha is working. Thanks in advance.

**Comment by xavierfoucrier** [comment]
Hello @jeronimus23!

See https://developers.google.com/recaptcha/docs/verify :wink:
