### ISSUE TITLE
Update lang attribute in html tag

### ISSUE THREAD

**Issue by mpodciwinski** [barbajs/barba#519]
Hi, 
since yesterday, I have been trying to update the `lang=""` attribute between pages, but with no effect.
Any ideas how to do that?

**Comment by xavierfoucrier** [comment]
Hi @mpodciwinski,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

I am closing the issue.
