### ISSUE TITLE
Beginners Guide

### ISSUE THREAD

**Issue by telagraphic** [barbajs/barba#520]
Hey All,

Since learning about Barba.js a couple months ago, I've struggled to get it working and finally got my head wrapped around it.

I've put together a [beginners guide](https://barba-page-transitions-guide.netlify.app/) to help people that are new to the library.  It's based on a real project where you can play with Barba.js and see how the documentation translates to real code.  

Let me know what you think and please offer any suggestions

https://barba-page-transitions-guide.netlify.app/

**Comment by xavierfoucrier** [comment]
Hi @telagraphic,

Thanks for your time making a page transition guide, but unfortunately **this is not the place where you can share it**. I repeat myself but issues are dedicated to Barba v2 implementation: I mean if you face a problem with the library, discover a bug, want to add a feature, etc.

For those kind of post, please **use the Slack workspace** in order to share and ask the whole community for feedback. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

Depending on feedback, your repository will be listed on the official Barba "useful links" documentation section: https://barba.js.org/docs/getstarted/useful-links/

Thanks for your understanding.
I am closing the issue.

**Comment by telagraphic** [comment]
@xavierfoucrier — Sorry!  I will post this in the slack channel, thanks for the clarification.
