### ISSUE TITLE
JavaScript file doesn't load after page transition

### ISSUE THREAD

**Issue by Navajocoding** [barbajs/barba#527]
Everything is working fine on my index.html. On the first .onload page all the images are draggable and all over the page  

**HERE THE PROBLEM:**

However, when **I WENT TO THE PAGE ABOUT.html AND GO BACK TO THE INDEX.html** my script look like isn't working anymore and I can see only one image that is not even draggable anymore.

Have a closer look to my project here:
https://codepen.io/cat999/project/editor/AEeEdg 

[![everything work fine on first onload page and images are draggable but when i go to the about page and come back on the index page the draggable is not working][1]][1]

 **HOW DO I FIX ISSUE? COULD SOMEBODY HELP ME TO FIX MY CODE?** 

`````
var winWidth = window.innerWidth,
    winHeight = window.innerHeight,
    threeWinHeight = winHeight*3;

$(window).on('resize', function(){
  winHeight = window.innerHeight,
  twiceWinHeight = winHeight*2;
});


$('.shape').each(function(){
  var topPos = Math.floor(Math.random()*1300),
      
      //BE CAREFUL 7000px is less then total body height or  CAUSING OVERFLOW
      leftPos = Math.floor(Math.random() * winWidth);
  $(this).css('top', topPos + 'px');
  $(this).css('left', leftPos + 'px');
});




Draggable.create('.shape', {
  //type:"rotation",
  bounds: '.section-2',
  edgeResistance:0.65,
  throwProps:true,
});



var number = Math.floor((Math.random() *15) + 2);
var number2 = Math.floor((Math.random() * 0) + -15);
var number3 = Math.floor((Math.random() * 0) + 15);
var number4 = Math.floor((Math.random() * 0) + 6);
$(".shape--circle").css("transform", "rotate(" + number2 + "deg)");
$(".shape--square").css("transform", "rotate(" + number3 + "deg)");
$(".shape--circle-2").css("transform", "rotate(" + number4 + "deg)");

`````

Additionally, the index and the about section has using barba.js.
Here the list of my script:

`````
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.4/TweenMax.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.4/utils/Draggable.min.js"></script>
<script type="text/javascript" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/ThrowPropsPlugin.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://unpkg.com/@barba/core"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.2.4/gsap.min.js"></script>
<script src="main.js"></script>
`````

  [1]: https://i.stack.imgur.com/AMOlF.gif

**Comment by xavierfoucrier** [comment]
Hi @Navajocoding,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

Anyway, I invite you to read the [`View` documentation](https://barba.js.org/docs/advanced/views/) section that will probably help you to make your code run as expected.

I am closing the issue.

**Comment by jgioegana** [comment]
I know this was a year ago already, but if I may add here, I encountered this issue last night. Please make sure of two things.

1.) In the Javascript file where you have the Barba init function, make sure you use **Views** as it will help you tell BarbaJS what to do before entering the page you're trying to enter. For more info, check this page: https://barba.js.org/docs/advanced/hooks/

I do it this way:
$(document).ready(function(){
    barba.init({
        sync: true,
        views: [
            {
                namespace: 'home-section', //specify the barba namespace you indicated in your HTML
                beforeEnter({ next }) { //before entering the next page and if it contains the 'home-section' namespace
                   // NOTE: You need to create individual script variables for each script you're going to load and add them one by one.
                   let script = document.createElement('script'); //create a script element
                   script.src = 'libraries/home-scripts.js'; //specify the directory of the script you want to load
                   next.container.appendChild(script); //this adds the script tag you created to the 'container' of this page
                }, 
            },
            {
                namespace: 'about-section', //specify the barba namespace you indicated in your HTML
                beforeEnter({ next }) { //before entering the next page and if it contains the 'about-section' namespace
                  // NOTE: You need to create individual script variables for each script you're going to load and add them one by one.
                    let script = document.createElement('script'); //create a script element
                    script.src = 'libraries/about-scripts.js'; //specify the directory of the script you want to load
                    next.container.appendChild(script); //this adds the script tag you created to the 'container' of this page
                }, 
            }
        ],
        transitions: [ //list the transitions you want on this section
            {
               async enter(data) { //Upon entrance
                    //you can put a function here that loads the animation upon entrance
                },
            },
        ],
    });
});


2. The most important part of my discovery upon resolving this issue. On your external JS script (the ones you are trying to import), if you are specifying some kind of init function that will load when after the page loads, make sure that you use **$(document).ready()** instead of window.onload(). 

For example, on my external JS I do this:

$(document).ready(function(){ //this is the part where I set mine to window.onload()
    init();
});

function init() {
    loadListItems();
}

I hope this helps!

**Comment by S-Fahmy** [comment]
what the **** is this ****** and i can see my scripts tags in the inspector but they are just not running after transition, meh just another wasted day and brain cells trying to figure out some ****** amateur frontend devs mess as usual.
