### ISSUE TITLE
How can i transition multiple divs with BarbaJS?

### ISSUE THREAD

**Issue by nikmors** [barbajs/barba#529]
I am experimenting on Barba.js for the first time. What i am trying to do is when transitioning from page to page, i want to see the animation of 3 colour-divs to load up first as a canvas effect ( On enter (from page 1) go to -> transition 1st div ( colour: a) ->go to  transition 2nd div ( colour: b) -> go to  transition 3rd div ( colour: c) -> then load page2 ).

Unfortunately, only the first canvas happens on load but the other two don't show after the first one. I tried a few combinations in main.js, i show you one of them. I also tried to have only one pageTransition(); where inside i create a gsap.timeline(); for the 3 divs. Yet it didn't work either. 

What do i do wrong? How can i run loading-screen-one, loading-screen-two & loading-screen-three the one after the other with barba.js?

You can see [here](https://codepen.io/nikmors/project/editor/ZjwMkk) more.

**Comment by xavierfoucrier** [comment]
Hi @nikmors,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

I am closing the issue.
