### ISSUE TITLE
Barba.js 2 Wordpress-Issues

### ISSUE THREAD

**Issue by fuenfminuten** [barbajs/barba#531]
Hi there,

I developed my own **WordPress** theme and use **Barba.js V2**. The transitions worked very well, but their are a big problem I couldn't solve:

When I click on a link in the main-navigation the current page-link gets normally a different style. The style refers to a class in the body element. But when I use barba the style didn't load.
What did I do wrong?

Thanks a lot for your help!!

**Comment by xavierfoucrier** [comment]
Hi @fuenfminuten,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

Anyway, using Barba **make your site work as a [SPA](https://barba.js.org/docs/getstarted/intro/#Intro)**, meaning that your browser doesn't really "reload" the whole site when navigating between pages: so the styles basically load from server side won't load automatically. You need to apply the CSS class programmatically: the best way is to update/refresh your current menu item using a [global hook](https://barba.js.org/docs/advanced/hooks/#Global-hooks).

Hope this help!
I am closing the issue.

**Comment by fuenfminuten** [comment]
I have found thins article from Feras Jobeir who wrote about how implement barba.js with wordpress. But the solution targets barba.js V1.

https://www.fjobeir.com/implement-barba-js-with-wordpress/

Can help to adapt this to Version 2?

Thanks a lot!!

**Comment by xavierfoucrier** [comment]
Hi @fuenfminuten,

As specified in my previous message, please **use the Slack workspace in order to ask the whole community for support**.

Thanks.
