### ISSUE TITLE
Sync mode doesnt work with @barba/css

### ISSUE THREAD

**Issue by danielschmid** [barbajs/barba#533]
I’m i right that the sync mode doesn’t work with barba/css ? When so it would be a useful feature.

**Comment by xavierfoucrier** [comment]
Hi @danielschmid,

You supposed well, this feature is not part of `@barba/css`, just because it's impossible to make `leave` and `enter` transitions to be concurrent with only CSS...

Can you confirm @thierrymichel?

**Comment by Jac733** [comment]
I just tried it today and it works like a charm! Could you show some code to see how you are attempting to do it?

**Comment by xavierfoucrier** [comment]
Hi @Jac733,

Can you provide a reproductible test repository to let me know how you make it works?
Thanks a lot.

**Comment by Jac733** [comment]
Here you go @xavierfoucrier !
I tested it on a live server, and setting `sync` to `true` or `false` affects each transition as expected.
[barba-css-test.zip](https://github.com/barbajs/barba/files/5033998/barba-css-test.zip)

**Comment by xavierfoucrier** [comment]
@Jac733 good job!

After checking the code of my local `@barba/css` test, I notice that I place the `sync: true` in the Barba root object instead of the `Transition` itself... that's why I haven't succeed to properly make it work! #fail :smile: 

Thanks for your packed code, it will help other people dive into `@barba/css` transitions.

I am closing the issue.
Have a nice day :wink:
