### ISSUE TITLE
Shared element transition using barba.js

### ISSUE THREAD

**Issue by bruno-henri** [barbajs/barba#536]
Hi, I'm studying barba.js v2 / GSAP, and I would like to know which way to make a transition similar to the video. 

[https://streamable.com/kl31t2](url)

Thanks guys!

**Comment by xavierfoucrier** [comment]
Hi @bruno-henri,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

I am closing the issue.

**Comment by bruno-henri** [comment]
Ok, thanks.
