### ISSUE TITLE
Page transition keeps scroll position

### ISSUE THREAD

**Issue by FearTheWild** [barbajs/barba#537]
Hello, I'm new to barba.js so just trying to get my head round it.

When a page transition is performed, my browser page scroll stays where it was. Is this intentional? 

Is it possible to have it so after the transition the next page is loaded at the top like normal?

Here is my code

`
     function pageTransition() {
	var tl = gsap.timeline();

	tl.to('ul.transition li', { duration: .5, scaleY: 1, transformOrigin: "top left", stagger: .2 })
	tl.to('ul.transition li', { duration: .5, scaleY: 0, transformOrigin: "top left", stagger: .1, delay: .1})
     }

     function contentAnimation() {
	var tl = gsap.timeline();

	tl.from('.hero', { duration: 1, translateY: 50, opacity: 0 })
     }

     function delay(n){
	n = n || 2000;
	return new Promise(done => {
		setTimeout(() => {
			done();
		}, n)
	});
     }

     barba.init({
	sync: true,

	transitions: [{
		async leave(data) {
			const done = this.async();

			pageTransition();
			await delay(500);
			done();
		},
		async enter(data) {
			contentAnimation();
		},
		async once(data) {
			contentAnimation();
		}
	}]
     });
`

**Comment by xavierfoucrier** [comment]
Hi @FearTheWild,

This is the **default browser behavior** when navigating through a SPA: as there is no reload when running page transition, you need to manage it yourself.

You need to use a **global hook** to tell your browser to scroll top when entering a new page.
There is an example in the documentation here: https://barba.js.org/docs/advanced/hooks/#Global-hooks.

In addition, you can also **prevent the browser from restoring the scroll position** when using backward/forward arrows using:
```js
if ('scrollRestoration' in history) {
  history.scrollRestoration = 'manual';
}
```

Finally, take the time to update your forking copy and refactor your code in order to avoid usage of `await delay(...)` in your transitions. See https://github.com/karanmhatre1/barba-page-transition-example/commit/c549e5097ffd4819ea8cfd598ce35995584d15c7.

Closing the issue :wink:

**Comment by mary-rika** [comment]
Hi , 

 barba.hooks.enter(() => {
  window.scrollTo(0, 0);
});

is working in html website but it's not working in wordpress. I tried so many codes but none is working . Do you have any idea ? 

Thanks

**Comment by mary-rika** [comment]
The issue was that my body element was set to height: 100% in css .It solved now
