### ISSUE TITLE
Problems with lightbox

### ISSUE THREAD

**Issue by replicant64** [barbajs/barba#540]
## The problem
I'm trying to implement a lightbox solution while using Barba.js - first I tried baguetteBox, then GLightbox, but they all throw errors. The underlying technique they use is `querySelectorAll` which seems to be the problem's source, since it would appear to need something like `data.next.container.querySelector()` but it only accepts selectors ..

How would I investigate further?

// Edit: Maybe if I exclude the barba link pointing at the big version image - is seems that's not possible anymore with `no-barba`, no?

**Comment by xavierfoucrier** [comment]
Hi @replicant64,

Sorry for the late reply.

As you noticed, **you need to target the right Barba container** with your lightbox library in order to only select links that will be present in the next page. Using `data.next.container.querySelectorAll("...");` is possible inside a `Transition` or a `View`, see https://barba.js.org/docs/advanced/hooks/#data-argument.

Excluding links is possible, but will not really help for targeting the right container in this case. See https://barba.js.org/docs/advanced/strategies/#prevent.

Let me know if you need more informations. :wink:

**Comment by replicant64** [comment]
Thanks, that cleared the issue for me. I look further library that let choose HTMLElement rather than just string of selector.

you are great work doing, keep up!
