### ISSUE TITLE
Reinitialize Javascript in Barba V3

### ISSUE THREAD

**Issue by mirmoc** [barbajs/barba#541]
Hi, 
The code works fine in Js outside Barba, but doesn't work through a view or global hook.
I couldn't find the answer for my code in similar topics.
Thank you

`{
		namespace: 'post',
		enter() {
			if(!!window.IntersectionObserver){
				const videos = document.querySelectorAll('video');				
				videos.forEach(video => {
					let isPaused = false;
					let observer = new IntersectionObserver((entries, observer) => { 
						entries.forEach(entry => {
							if(entry.intersectionRatio!=1  && !video.paused){
								video.pause(); isPaused = true;
							}
							else if(isPaused) {video.play(); isPaused=false}		
						});
					}, {threshold: 1});			
					observer.observe(video)
				})
			}
		}
	}`

**Comment by mirmoc** [comment]
Or I could use it with one global hook, but still doesn't work. Can anyone help?

**Comment by xavierfoucrier** [comment]
Hi @mirmoc,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

Anyway, **Barba v3 doesn't exist yet**... please be patient :smile: 

I am closing the issue.
