### ISSUE TITLE
Async breaks navigation betwwen pages

### ISSUE THREAD

**Issue by adrilevendi** [barbajs/barba#545]
Overall problem is that the transition doesnt play, the page makes a quick refresh and then its back to the same page. It works well without async. Also it does work with async on pure html/css.
-- Using Wordpress 5.4.2 and  Timber 1.13

## **JS:**

```js
import barba from '@barba/core';


//Page Transitions

function delay(n) {
  n = n || 2000;
  return new Promise(done => {
    setTimeout(() => {
      done();
    }, n)
  })
}

function pageLeaveAnimation () {
  // $('#sideMenu').removeClass('active');

  var t = gsap.timeline();

  t.to('.transition',
    {
      width: "100%",
      duration: 1
    });

    t.to('.transition', {
      x: "100%",
      duration: 0.5
    });

    t.set('.transition', {x:0, width: 0});
}



$(function () {
  barba.init({
      sync: true,
   
    transitions: [{
       async leave(data) {
  
        const done = this.async();  
        pageLeaveAnimation();
  
  
        await delay(1000);
        done();
  
  
      },
       async enter(data) {
      }
    }],

  });
  
});
```

## **LAYOUT SETUP:**

```twig
{% block html_head_container %}

    {% include 'html-header.twig' %}
    {% block head %}
    {% endblock %}
    </head>
{% endblock %}

<body data-barba="wrapper" class="page-{% block body_class %}{% endblock %}" data-template="base.twig">


<div class="transition"></div>

<main data-barba="container" data-barba-namespace="home" id="content" role="main" class="content-wrapper">
<header class="header">
    {% block header %}

        {% include "header.twig" %}

    {% endblock %}
</header>
    <div class="wrapper {{ sidebar_class }}">
        {% block content %}
            Sorry, no content
        {% endblock %}
    </div>
    {% if sidebar %}
        <aside class="layout-sidebar">
            {{ sidebar }}
        </aside>
    {% endif %}
</main>

{% block footer %}
    <footer id="footer">
        {% include 'footer.twig' %}
    </footer>
    {{ function('wp_footer') }}
{% endblock %}


{# <script type="text/javascript" src="//code.jquery.com/jquery-2.2.4.min.js"></script> #}

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="{{ site.theme.link }}/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/debug.addIndicators.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.3.4/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.4.0/ScrollTrigger.min.js"></script>

<script src="{{ site.theme.link }}/dist/js/index.min.js"></script>



</body>
</html>
```

Thank you

**Comment by xavierfoucrier** [comment]
Hi @adrilevendi,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

I notice you are using the wrong/old version of the Karan community repository, please update your forking copy and refactor your code in order to use the appropriate syntax. For more informations see https://github.com/karanmhatre1/barba-page-transition-example/commit/c549e5097ffd4819ea8cfd598ce35995584d15c7.

As **Barba is working "client-side"**, using WordPress or another CMS won't give a different result. Sync mode requires the next page to be fully loaded to play the `leave` and `enter` transitions together, see https://barba.js.org/docs/advanced/transitions/#Sync-mode. Having a transition that work well on pure HTML on a local host doesn't mean is should work well on a CMS hosted on a web server, because latency is something you don't have locally. Using the latest Karan version should do the trick.

I am closing the issue.
