### ISSUE TITLE
slider error

### ISSUE THREAD

**Issue by mesutuca33** [barbajs/barba#546]
hello i'm new at this job My problem is that the slider works when the page is first loaded, when I switch to another page and return to the page with the slider, the slider does not work. can you help me please. I'm new here, I don't know how to do it, I would be very happy if you help him.

Video of my fault is available in the link

[Videos](https://youtu.be/MV5EPdPFqf4)

**Comment by xavierfoucrier** [comment]
Hi @mesutuca33,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

In addition, you must take a look at `View` in the documentation, see https://barba.js.org/docs/advanced/views/. This allow you to run custom code, like "initialize my slider", when you enter a specific page. You need to setup `namespaces` first, see https://barba.js.org/docs/getstarted/markup.

Hope this help :wink: 
I am closing the issue.

**Comment by mesutuca33** [comment]
I don't know how to do it, I don't know

**Comment by xavierfoucrier** [comment]
Hi @mesutuca33,

First of all, start by reading the documentation: there is code sample inside about markups, namespaces, views, etc.. Next, if you are unable to make it work, join on Slack and ask the community for support.

Thanks :wink:
