### ISSUE TITLE
How to pass data based on the page being transitioned to?

### ISSUE THREAD

**Issue by ZachSaucier** [barbajs/barba#551]
I created a wipe effect similar to the one used between pages in the Barba docs. However I'd like to change the color of the wipe based on the page being transitioned to. Obviously I could create a mapping of page URLs to color in a regular JS object and use that inside of Barba's enter callback, but is there a more Barba-y way of keeping data like that depending on the page being transitioned to? If not I'll keep with the regular JS object method I have.

**Comment by xavierfoucrier** [comment]
Hi @ZachSaucier,

This can be achieved in many different ways, depending on your project layout/structure, but the more relevant way for me is to have a **key/value pair with url/color**. It's easy to update if you have another page to add or remove from your site.

You can then make it change in one of the Barba [`hooks`](https://barba.js.org/docs/advanced/hooks/) by reading the `data.next.url` in order to grab the appropriate color.

Hope this help :wink:
I am closing the issue.

> Be careful, the [`data` argument](https://barba.js.org/docs/advanced/hooks/#data-argument) is build based on the [lifecyle diagram](https://barba.js.org/docs/getstarted/lifecycle/).
