### ISSUE TITLE
How to use it with Vue.js?

### ISSUE THREAD

**Issue by zxb79554227** [barbajs/barba#553]
I don't wanna build a project init from 0, but I still wanna use React or Vue (MVP)system to build the project. tho I like barba transition system, How can I use both Vue and barba in my project

**Comment by xavierfoucrier** [comment]
Hi @zxb79554227,

When using a front-end framework like **React, Vue or Next**, you should take a look at the framework documentation and use everything the framework is bringing you, like page transitions, routes, etc. instead of trying to implement another library over a complex framework layout.

For now, we haven't planned to make a dedicated section into the docs about this because most developers doesn't implement Barba over those kind of frameworks. May be add a new one in the future. I am closing the issue :wink: 

> `@barba/css` plugin is inspired by [VueJS transition system](https://vuejs.org/v2/guide/transitions.html#Transition-Classes), so you should use the Vue classes instead of implementing our plugin.
