### ISSUE TITLE
Chrome warning: DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by clmsftsw** [barbajs/barba#554]
I always get the following warning message in Chrome when using barba through an cdn:

DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/@barba/barba.umd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I tried jsdeliver and unpkg. I get always the same warning. It is still working as expected though.

**Comment by Dushyant1295** [comment]
I am Using Webpack alsoe getting same issue for 

DevTools failed to load SourceMap: 
webpack:///node_modules/@barba/prefetch/dist/barba-prefetch.umd.js.map: 
HTTP error: status code 404, 
net::ERR_UNKNOWN_URL_SCHEME

**Comment by auliamnaufal** [comment]
i use barba from npm and the response is this: 
"Uncaught SyntaxError: Cannot use import statement outside a module"

**Comment by xavierfoucrier** [comment]
Hi @auliamnaufal,

Following a tutorial is not sometimes sufficient, just do a simple request on a search engine will give you the answer.

Anyway, you are off-topic here!

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer
