### ISSUE TITLE
Page reloaded on first time links

### ISSUE THREAD

**Issue by stefano76** [barbajs/barba#562]
Hi,

I use Barba js v.2, in a Wordpress site.

The first time I click on a link the page changes in the address bar, but immediately it redirects on my page. The second time I click on the same link, the page changes and the transition works perfectly.

Why do I need to click two times on the same link to change the page and make the transition working?

I use also the plugin W3 Total Cache on Wordpress. Any conflict?

Thanks!

**Comment by Sanady** [comment]
Can you please show how you use V2 in WP? I have simular issue

**Comment by xavierfoucrier** [comment]
Hi @stefano76,

Barba v2 has already been tested on WordPress and there is no major issues when implementing it on this CMS.
You can try to disable the W3 Total Cache plugin and see if it's better.

In addition, you have **probably an error inside one of your transition**.
Have a look at the `debug` option here: https://barba.js.org/docs/advanced/recipes/#Debug-with-Barba.

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

I am closing the issue.

**Comment by stefano76** [comment]
> Can you please show how you use V2 in WP? I have simular issue

In javascript file I have this:

`barba.init({
    debug: true,
    logLevel: 'debug',
    
    transitions: [{
      name: 'home-transition',
      //sync: true,
      from: {
        namespace: [
          'home'
        ]
      },
      beforeLeave(data) {
        // create your stunning leave animation here
        $('.main-home').addClass('slide_home_out');
      },
      enter(data) {
        // create your amazing enter animation here
        $('.main-' + data.next.namespace).addClass('slide_child_in');
      }
    }, {
      name: 'back-transition',
      //sync: true,
      to: {
        namespace: [
          'home'
        ]
      },
      leave(data) {
        // create your stunning leave animation here
        $('.main-' + data.current.namespace).addClass('slide_child_out');
      },
      enter(data) {
        // create your amazing enter animation here
        $('.main-home').addClass('slide_home_in');
      }
    }]
});`

In header.php, I add "data-wrapper" to body:

`<body data-barba="wrapper">`

And in the custom template file (content) I add "data-barba" and "data-barba-namespace" attributes:

`<main data-barba="container" data-barba-namespace="home" class="main-home">`

**Comment by Ihatetomatoes** [comment]
Hi @stefano76, you are trying to add and remove classes to make the transition.

Barba has a CSS plugin that does just that, so all you have to do is to add css to your stylesheet.

https://barba.js.org/docs/plugins/css/
