### ISSUE TITLE
Simple "hello world GSAP" - "leave" example not working (Page changed immediately)

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [barbajs/barba#567]
I do not understand why the `leave` transition not working.
https://brave-golick-c4b1cd.netlify.app/index.html

** Update:
Looks like a bug related to https://codesandbox.io/ projects

**Comment by xavierfoucrier** [comment]
Hi @Ezra-Siton-UIX,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

> This place is made for **BarbaJS issues and library bug report**, so  you won't get "instant help" here until you join the Slack community. Do not spam here. Read the docs carefully and take time to search before posting any other issue.
