### ISSUE TITLE
Regarding individual transition animations for different pages.

### ISSUE THREAD

**Issue by ksh-r** [barbajs/barba#572]
Hello,
First of all, I'm not sure if this should be an "issue", but I couldn't find a Barba specific forum, so I'm posting here. I am sorry if I have offended anyone.

I am building a website with multiple pages and I have different transitions for each of them. I don't know how should I approach this scenario using Barba JS.
I have read the docs and I have understood that we can use "Enter" and "Leave" functions to define transitions. Enter is for defining animation that will be played while entering next page and Leave is for defining animation that will be played before leaving the current page.
My question is how to define the animation which will be played after entering the Home page. There is no "previous page", so where should I define the loading animation for Home screen? (Currently, I have defined it in View of home page using beforeEnter() but I am not sure if that's the correct way). I also have different transitions for different pages so how should I tackle this (using transition rules?)

Any input is highly appreciated. Thank you.

**Comment by xavierfoucrier** [comment]
Hi @ksh-r,

The **"first browser load"** transition is managed by the `once` hook.
Take a look at the `Hooks` documentation here: https://barba.js.org/docs/advanced/hooks.

You can define different transitions between pages using Barba "transition resolution" system based on `Rules`, see https://barba.js.org/docs/advanced/transitions/#Rules. This is the better place to build your custom transitions. Without rules, the declared transition will be use as default one, see the basic transition example here: https://barba.js.org/docs/getstarted/basic-transition/.

`Views` are made to run "custom code" based on page/namespace, like initializing a slider or a another third party library.

As you guess, this is not the better place for asking questions...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

I am closing the issue.
