### ISSUE TITLE
Optimising multiple custom conditions

### ISSUE THREAD

**Issue by seamofreality** [barbajs/barba#575]
Hello,

I have a more general question on how to optimise custom conditions.
I've implemented six transitions with custom triggers and one default transition. The default transition is the very last of my transitions. The custom triggers are either checking for a certain class on the trigger element or go by checking from/to namespaces. 

Simplified my conditions look like this...

```javascript
barba.init({
        transitions: [
            {
                name: 'shared-via-filter',
                from: {
                    custom: ({trigger}) => {
                        return trigger.classList && trigger.classList.contains('transition-via-filter');
                    },
                },
                ...
            },
            {
                name: 'shared-via-pagination',
                from: {
                    custom: ({trigger}) => {
                        return trigger.classList && trigger.classList.contains('transition-via-pagination');
                    },
                },
                 ...
            },
            {
                name: 'project-via-teaser',
                from: {
                    custom: ({trigger}) => {
                        return trigger.classList && trigger.classList.contains('project-hero__link');
                    },
                },
                ...
            },
            {
                name: 'search-via-menu',
                from: {
                    custom: ({trigger}) => {
                        return trigger.classList && trigger.classList.contains('search-trigger');
                    },
                },
                ...
            },
            {
                name: 'search-via-search-page',
                from: {
                    namespace: ['search-page']
                },
                to: {
                    namespace: ['search']
                },
                ...
            },
            {
                name: 'search-via-search',
                from: {
                    namespace: ['search']
                },
                to: {
                    namespace: ['search']
                },
                ...
            },
            {
                name: 'default',
                ...
            },
        ]
    });
```

Now I've noticed that there is a perceivable delay before the leave transition of my page transition is starting. I did some investigations and it seems to me it depends on how many other conditions have to be checked before it can find the right transition for the page.

Maybe this is all just a big coincidence, but I'd rather ask:
Is there anything I need to be aware of that could slow down checking the trigger conditions and delay my transition?
Or any other thing that could influence how soon the leave transition can be played?

Thanks a dozen!

**Comment by xavierfoucrier** [comment]
Hi @seamofreality,

Thanks for pointing this.
Hard to tell without seeing the code/website live...

From my experience, having multiple rules/conditions to choose the appropriate transition is not a problem... except if your tests use hard javascript parsing/stuff inside each rule of course, but it doesn't seems to be the case here.

Barba wait for the next page to be prefetched before leaving the current one, so if your next page is too big (contains image stuff or is waiting for a server-side rendering content that could take time), there could be a delay before the transition to come, and in some cases a timeout error.

You should take a look at the [@barba/prefetch](https://barba.js.org/docs/plugins/prefetch/) plugin in order to **prefetch in-viewport links**: this can probably reduce/remove the delay before the leave transition starts.

Hope this help!
I am closing the issue :wink:
