### ISSUE TITLE
browser back button and data-barba-prevent

### ISSUE THREAD

**Issue by benzkji** [barbajs/barba#582]
I've implemented barba and everything works fine. also, I have some pages that use third party javascript widgets from various sources (it' a hotel...so, it's Protel and trustyou, for those who know), that dont work when using a page transition, as the javascripts are not run. for those pages I am using `data-barba-prevent`, what works very well. 

just one thing is bothering me: after having visited such a page, navigating away from it (with barba transition) using the browsers back button does bring me back, with a transition. so, in that case, the js widgets again are not working anymore.

how can I tell barba.js to NOT transition, when getting back with the browser button?

**Comment by xavierfoucrier** [comment]
Hi @benzkji,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

Well, about your question, you are not taking the problem in the good direction, because I guess you may prefer to properly run your third party plugins with javascript, and this is possible using Barba `Hooks`. See https://barba.js.org/docs/getstarted/custom-code/.

Of course, if your third party plugins are more complex than just "calling a javascript method" to init them, you should use `prevent` strategy to "hard reload" the page, what you did. In addition, you may tell Barba to "play" a different transition when the user is clicking on back/forward browser buttons by checking the `data.trigger` parameter in the `Transition`, then see if the transition is called by those buttons, and adjust the transition. See https://barba.js.org/docs/advanced/hooks/#Parameters.

Keep in mind that **Barba is designed for Single Page Application**, and not playing a transition when using backward/forward browser buttons is not part of the library internal logic.

**Comment by benzkji** [comment]
thx. sorry wasnt aware of the other channels.

**Comment by xavierfoucrier** [comment]
@benzkji no problem, hope this help, if not feel free to contact me on Slack :wink:
