### ISSUE TITLE
Js scripts won't load with transition

### ISSUE THREAD

**Issue by jalissaw** [barbajs/barba#593]
I have a simple function where you click on an icon an the menu is supposed to drop down. However, when the page transitions, the event won't work. It only works when I reload the page. I have tried to append the file to head but that doesn't work. I have put the function inside the views parameter. I have been researching this problem for quite a while and I am at a lost for how to fix it. How can I get my script to load the first time? 

Here is the code I ran in views : 
views: [{
        namespace: 'home',
        beforeEnter({ next }) {
            // update the menu based on user navigation
            // load your script
            let script = document.createElement('script');
            script.src = 'menu.js';
            next.container.appendChild(script);
        },
        afterEnter() {
            // refresh the parallax based on new page content
            console.log('after')
        }
    }],

**Comment by xavierfoucrier** [comment]
Hi @,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

Just to let you know, this code should produce a `<script>` tag every time you enter the `home` view, not every time you transition to another page. Take a look at "global hooks" inside the documentation to run code globally along all pages, see https://barba.js.org/docs/advanced/hooks/#Global-hooks.
