### ISSUE TITLE
How can i make a delay before transition start?

### ISSUE THREAD

**Issue by BaranovRoman** [barbajs/barba#595]
Sometimes you may need add some delay, before transition start, for example preloader, or age confirmation, i didn't find how to do it, for now my transition animations placed on views, i think it`s wrong, but I can't think of a better way to do it

**Comment by xavierfoucrier** [comment]
Hi @BaranovRoman,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

Note that if you just want a delay before a transition start, you can just add this one using `delay` property of your animation library, like with `gsap`. For age confirmation or preloader, you need to call `barba.init` when these "stages" are completed :wink:.

**Comment by BaranovRoman** [comment]
sorry for creating issue, and thank you very much for reply!
