### ISSUE TITLE
Partially load container content

### ISSUE THREAD

**Issue by scottwvw** [barbajs/barba#600]
I'm new to Barba JS, and struggling to work out if the below is possible and how to achieve it.

When coming to the page from elsewhere on the site, the container would update as normal - however when landing on the archive page (in wordpress) and clicking a link to a single post (from from the left-hand column), the content on the left column would remain as is, and the content on the right would update with new content (see diagram below).

Any pointers greatly appreciated!

Thanks

![image](https://user-images.githubusercontent.com/7535883/104479927-dffbd280-55bb-11eb-9938-9c8ea8ddc6b0.png)

**Comment by xavierfoucrier** [comment]
Hi @scottwvw,

Sorry for the late reply :roll_eyes: 

BarbaJS doesn't offer a way to just update a part of the container, but you can do it using the modern `Fetch` API, here is some documentation: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch. This way you will be able to keep Barba for all the pages, except for loading column 2 content.

> Don't forget to use polyfill depending on brower support you want, have a look at https://github.com/github/fetch.

You can also use the [internal Barba `request` utility](https://barba.js.org/api/modules/_core_src_utils_request_.html#request), this will set the `x-barba` request header when calling your URL.

In any situation, be sure that your content 2 request only return HTML content like `<div>`, `<article>` or something, and not plain `HTMLDocument`: otherwise, you will need to "extract" the content from the document before injecting it in the DOM.

I am closing the issue.
Happy coding with Barba :tada:
