### ISSUE TITLE
Keep old page visible while transitioning

### ISSUE THREAD

**Issue by LeoDav22** [barbajs/barba#605]
Hi, I'd like to make a transition where the old page remains visible while the new page slides on top of it. But the old page keeps disappearing before the transition starts.
I saw this issue that is exactly the same as mine : https://github.com/barbajs/barba/issues/85 . But I'm not sure the answer matchs, as it was on barba first version.

Thanks for your help !

**Comment by xavierfoucrier** [comment]
Hi @LeoDav22,

Thanks for getting in touch!

You need to use the `sync` option in order for Barba to "wait until the next page is available: fetched or cached".
See https://barba.js.org/docs/advanced/transitions/#Sync-mode.

In order to keep your previous page visible, you should not play a "leave" transition, more an "enter" one: this way your previous content will remain unchanged until the next page is fetched/cached and the "enter" transition will play. Have a look at the lifecycle diagram here in order to fully understand the page transition process: https://barba.js.org/docs/getstarted/lifecycle/.

> You get it, the issue was about the v1 :wink: 

I am closing the issue.
Happy coding with Barba :tada:
