### ISSUE TITLE
Browser reload affects header and nav 

### ISSUE THREAD

**Issue by nvminhhieu** [barbajs/barba#609]
This is my first project using Barba and I encountered this problem that I can't wrap my head around! 

I place my nav and header and CDN library in between **data-barba="wrapper"**  and **data-barba="container"** in my index.html just like in documentation. Then I'm going to another page, which doesn't have nav and header, the nav and header get carried over and work fine! However, if I reload the page, the nav and header disappear. 

I want that if user reload on another page, it still have the nav and header. So how can I fix this problem? 

A snippet of my code :
```
<body>
   
    <main data-barba="wrapper">  
       //Background, Nav, Menu, Header,.....

            <div data-barba="container" data-barba-namespace="home">
            // Home page content
            </div>

            //CDN, javascript
     </main>

</body>
```

**Comment by xavierfoucrier** [comment]
Hi @nvminhhieu,

Looks like a server side issue for me.

You should have your nav+menu+header on all your pages before starting using Barba, because everything outside of the container but inside the wrapper will be kept between page transitions, here is the point, and that's why when reloading the page it disappear...

Let me know if its clear for you :wink:

**Comment by nvminhhieu** [comment]
Thank you! By putting nav+header in between wrapper and container, it does solve the issue!

However, after I reload the other page, if I want to go back to the main page, the page transitions does not run. What is the possible fix for this?

**Comment by xavierfoucrier** [comment]
@nvminhhieu duno why, first of all you should run Barba in `debug` mode, because if your transition fail outside of this mode, you won't be able to debug anything, or you will face some difficulty to debug: this is the most common problem when implementing transitions.

Have a look at the documentation here: https://barba.js.org/docs/advanced/recipes/#Debug-with-Barba

**Comment by xavierfoucrier** [comment]
@nvminhhieu Please don't forget to close the issue if you don't have further questions related to your main problem. Feel free to join the Barba Slack workspace if you need more help :wink: 

> See https://barba.js.org/docs/getstarted/useful-links/#Developer.
