### ISSUE TITLE
Pass the trigger event through `hooks`

### ISSUE THREAD

**Issue by adamrzk** [barbajs/barba#622]
I am using the `leave` function to make some transition. I am not applying the transition on the container itself but on another element outside it. How can I get the click event in `leave` function? my transition needs the e.pageX and e.pageY values

**Comment by mestrellar28** [comment]
Hello @xavierfoucrier 

Any docs where you explain how to update the nav-link active class on navigation when the main navigation is out the data-barba: container??? thanks a lot

**Comment by xavierfoucrier** [comment]
Hello @mestrellar28,

Unfortunately no, but it's not complicated: you just have to target the right `container`, using `data.current.container` or `data.next.container` in the appropriate `Hook`, then target your nav by simply using a `document.querySelector('.my-nav')` and finally change your active class.

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

> I will mark your comment as off-topic...
