### ISSUE TITLE
Is it possible to implement infinite scrolling, .append()

### ISSUE THREAD

**Issue by alekssskirov** [barbajs/barba#625]
Is it possible to implement infinite scrolling, pagination, or a "Show more" button»
Example. append
https://www.jqueryscript.net/demo/AJAX-Based-jQuery-Load-More-Pagination-Plugin-loadMore-js/

**Comment by xavierfoucrier** [comment]
Hi @alekssskirov,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

Quick answer: yes, it is possible.
The new loaded content will just remain in the current Barba container, simply using asynchronous loading.
