### ISSUE TITLE
Update help code for disabling BarbaJs Wordpress wp-admin v2

### ISSUE THREAD

**Issue by Louboutin1017** [barbajs/barba#626]
I'm relatively new to Barba and loving it. Currently, I am working on a project on WordPress.

When I landed on "Homepage" and navigate to "About Us" page, and if I need to edit the "About Us" page, the wp-admin link "Edit" will open "Homepage" Even the "Customize" link disappears.

Research:
I found a couple of user issues, and the codes are for Barba v1, and they don't work.

Suggested solutions:
1. If user is admin and logged in, disable Barba, but Barba will work for other users logged in or not.
2. a code to fix the link issues. (I think I prefer this better)

Slack community:
I already joined it, searched and asked for help on it, but nothing yet.

**Comment by xavierfoucrier** [comment]
Hi @Louboutin1017,

**No need to open an issue if you already asked the question on Slack, waiting for the appropriate answer is better than asking everywhere the same one.**

The better solution for me is the number one: you need to disable Barba when you are logged in. Trying to "fix links" inside WordPress admin bar could result in other issues when upgrading to a next WordPress version, because as you guess, WordPress team can change the element structure at any time.

Some developers also disable the admin bar when navigating on the website to prevent this kind of issue. You can also use a custom `prevent` test for that, as suggested on Slack, see https://barba.js.org/docs/advanced/strategies/#prevent.

Feel free to ask again on Slack if needed.
I am closing the issue.
