### ISSUE TITLE
Page Reloads  while navigating to other pages on slow networks.

### ISSUE THREAD

**Issue by Dushyant1295** [barbajs/barba#628]
Hello Sir 🤍
                   Thanks For this library . . .  

I'm Facing an Issue while navigating between two pages   
as on Homepage there is a video, so Homepage take long time to load

also  How can we load all assets ( img, videos  etc ) of next page using barba.prefetch in idle time 

[  home.php --> about.php  ] page reloads and not navigating to about.php page on Slow Network .

i'm Using Barba prefetch  

```

barba.use(barbaPrefetch);

barba.init({
  sync: true,
  preventRunning: true,
  timeout: 5000,
  transitions: [
    {
      name: "dpk-transition",
      async once({ next }) {
        smooth(next.container);
      },
      async leave({ next }) {
        const done = this.async();
        pageTransition();
        await Delay(1000);
        done();
      },

      beforeEnter({ next }) {
        init();
      },
    },
  ],

  views: [
    {
      namespace: "curtain",
      afterEnter({ next }) {
        curtainEffect();
      },
      beforeLeave({ current }) {
        destroyPlane();
      },
    },
  ],
});


```

Here is the live Site we can inspect and see while selecting 3g Slow network mode http://brahmandjyotish.com/

**Comment by xavierfoucrier** [comment]
Hello @Dushyant1295,

If the page reloads, it's because it takes more than 5 seconds - `timeout: 5000` - to load the next document. **Barba doesn't care about page assets**, it just care about the document, so if you don't get the document in the timeout laps, your server takes too much time to answer.

Barba prefetch is not meant to load assets, even in idle time: this is your job, based on what you need on your site :wink: 

> As a side note, avoid using `await delay` syntax for transitions, prefer using the internal animation library delay method, see https://barba.js.org/docs/getstarted/basic-transition/#Animation.

**Comment by Dushyant1295** [comment]
Thanks Sir ! I Got It  Thanks For  Helping me Out 🤍
