### ISSUE TITLE
MutationObserver doesn't work when using back/forward buttons.

### ISSUE THREAD

**Issue by Iraklikandelaki** [barbajs/barba#631]
I use MutationObserver to animate several divs, it's fine when you go to  the link, but once you go back or forward, MutationObserver fails to respond, the divs have the original classes and doesn't get any classes on scroll whatsoever.

**Comment by xavierfoucrier** [comment]
Hi @Iraklikandelaki,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
