### ISSUE TITLE
Transition gets cut if trigger has 'mouseover' event

### ISSUE THREAD

**Issue by gmzbri** [barbajs/barba#632]
Hello!
I'm implementing a 'cover' type transition where a splash screen shows when leaving a specific namespace and disappears when entering the next one.

The trigger to this transition has some 'mouseover' events interacting with other elements on the page.
I'm experiencing an issue where this transition gets cut because of those events (if I remove all the events it works fine).

Is there an already known workaround for this situation or it might be simply related with an error on my code?

Thanks!

**Comment by xavierfoucrier** [comment]
Hi @gmzbri,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

Anyway, I guess if the mouse events interact with previous - `current` - container, you should try to first disable them nicely and then start your transition, otherwise, your transition won't looks smooth and user will be able to continue to interact with the previous page until the cover shows up, so it will lead into a bad user experience. Disabling them is the better option, mostly if `mouseover` events are linked to elements that will disappear after page transition.
