### ISSUE TITLE
Barba CSS Leave Transition Cuts Short

### ISSUE THREAD

**Issue by BritLuey** [barbajs/barba#633]
So I've noticed a problem where the leave animation on my page gets cut short randomly from time to time leading to a visible jump between pages which is driving me crazy. I've spent four hours today trying to figure out whats going on and here is what I have done and found / expect:

- I stripped all other Javascript from my page, so I was only using Barba & the BarbaCss plugin
- I was attempting a simple 400ms opacity transition between pages, implemented directly from the documentation

(So pretty basic stuff that anyone can replicate)

The issue seems to be that the Leave state cuts off early and it jumps straight to the Enter state
- Timing wise I expect I only get about 150/200ms of the Leave animation before it switches to the next step

I tried for hours switching between pages trying to figure out what causes this to happen:
- Seems to happen when clicking through pages quickly
- I tried debugging, but watching the source in the inspector was clearer
- I suspect if you're navigating through the page rapidly and you don't hover over a link for long enough (Which I understand has some effect which preloads the next page) something goes haywire and causes the animation to cut short. 

I've only been using Barba for a week so maybe someone with better knowledge can figure out what's going on

**Comment by xavierfoucrier** [comment]
Hi @BritLuey,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

If this only happen when clicking though pages quickly, I suggest you to enable the `preventRunning` option: this prevent Barba from breaking your current transition when clicking on another link. By default, this option is set to `false`. See https://barba.js.org/faq/#How-to-prevent-transitions-to-break.
