### ISSUE TITLE
Prefetch or update already fetched url

### ISSUE THREAD

**Issue by codeplaygoa** [barbajs/barba#636]
is there a way to call barba.prefetch(url) again for the latest updated post, if already fetched.
In my wordpress site with comments, i am saving comments via ajax and these comments are approved automatically.
Now when you navigate between the pages and comes back on the same post, the newly added comment wont show up.

**Comment by xavierfoucrier** [comment]
Hello @codeplaygoa,

It's possible to prefetch a page that has already been prefetched: you need to set option `cacheIgnore: true` in order to disable page caching. However, you will lost the opportunity to save bandwidth if you disable it. You can also disable the cache for a specific list of URLs, but you will need to use the `@barba/router` plugin for this. Read more here: https://barba.js.org/docs/advanced/strategies/#cacheIgnore.

The other way would be to use a Barba `Hook` to load comments asynchronously when navigating to the page that contain them. This way, the content of the page that don't change, your "article", will stay the same, and the comments section bellow will be loaded asynchronously with another fetch request (manually made) to get all comments, including the new one.

Hope it's clear :wink: 
Feel free to close the issue.

**Comment by codeplaygoa** [comment]
@xavierfoucrier thanks for the reply. I am currently loading the comments asynchronously on page enter.
But unfortunately both the above solutions are not slightly ideal for me.
It would be really cool if i can keep the `cacheIgnore:true` and have a feature to update the local xhr cache for a specific url. 
Hoping to see that feature in future.

**Comment by xavierfoucrier** [comment]
For now it's not possible, sorry. Using an `enter` hook and load your comments asynchronously is the best way to get your new comments with ease. I will talk about this feature to the other team members.

Closing the issue :wink:
