### ISSUE TITLE
No click event / hook when using Sync mode?

### ISSUE THREAD

**Issue by sebszocinski** [barbajs/barba#651]
When using sync mode and clicking a link, there is no way of setting a body class or showing a loading overlay etc to tell the user something is happening in the background. Does this need to be handled externally?

**Comment by sebszocinski** [comment]
Sorry I should have mentioned I did read the docs and was aware of that, but thought surely there must be a way to handle an event when clicking on an internal link since Barba already does that... I feel like this should be a feature? I can't think of a reason where you would use the Sync mode and not want some kind of user notification.

Could we not just have Barba add a body class of "barba-fetching" or something?

**Comment by xavierfoucrier** [comment]
Hi @sebszocinski,

Thanks for your feedback.

Well, probably having a class won't help a lot, since we are talking of milliseconds here to fetch a web page - most time - so the class will probably appear, then disappear too fast.

Anyway, I just though about something that should work for you: the `prevent` strategy, see https://barba.js.org/docs/advanced/strategies/#prevent. This will be called before any Barba specific stuff related to hooks or transitions.

Have a try and let me know :wink:
