### ISSUE TITLE
Forms? 

### ISSUE THREAD

**Issue by infosisio** [barbajs/barba#660]
Sorry for posting this but I went through all the past relevant questions and haven't found a specific example that deals with this.

I saw that barba does not support post forms, so I went with the ajax path, however they are not working properly. Disabling the form links is something possible but that means no smooth transitions.

Would you consider documenting a simple and clear path of how to combine barba with forms of any type, while maintaing transitions? 

I think that would be very helpful to many.

**Comment by infosisio** [comment]
Update: I managed to get ajax works to form, however when using barba.go to redirect back, I have to follow with a             window.location.reload() call to get the fresh version. Is there a better way to make barba fetch the latest version and go to it? Doing a prefetch before go does not work.

**Comment by infosisio** [comment]
Figured it out, it was something else causing this.

**Comment by xavierfoucrier** [comment]
Hi @infosisio,

Having a clean example inside the documentation won't have a sense here, since your issue is not related to Barba, but more "how to manage a form into an SPA application?".

About your location reload, well, if you use AJAX calls, you just have to get the server answer and display a clean message on your page like "ok the form was sent" / "sorry, there was a problem sending your request".

Happy coding with Barba :tada: 

> There is a Barba util method to hard reload a page, see `barba.force` into https://barba.js.org/docs/advanced/utils/.

**Comment by infosisio** [comment]
@xavierfoucrier Thanks for the answer, yes I figured everything out, barba.go works perfectly if the cache is disabled. It was some thing else in my application getting things stuck.
