### ISSUE TITLE
`Uncaught SyntaxError: Cannot use import statement outside a module`

### ISSUE THREAD

**Issue by milindgoel15** [barbajs/barba#666]
Sorry for not following according to the given template.

So I was using Barba js via cdn all this time and it works flawlessly. Now I decided to use Barba via npm which I successfully installed using `npm install @barba/core`. However, when I import this node module in my barba.js file, this error comes in the browser console:

`Uncaught SyntaxError: Cannot use import statement outside a module`

I have tried both import and require but it still doesn't work. Could anyone guide?
I had pasted my barba.js code [here](https://katb.in/xedajubifug) to reproduce or investigate the issue.

**Comment by xavierfoucrier** [comment]
Hi @milindgoel15,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

> If you want to `import` a module inside a `.js` file, you need to use `type="module"` attribute on your `<script>` tag.

**Comment by milindgoel15** [comment]
> If you want to import a module inside a .js file, you need to use type="module" attribute on your <script> tag.

Yes, I had tried this as well but didn't work. Sure I will post my query on slack for further  help.
