### ISSUE TITLE
Working with forms?

### ISSUE THREAD

**Issue by abramowsergey1992** [barbajs/barba#667]
I connected Barbra to the site and everything is fine, but I can't bind the script to the forms.
When submitting a form (post, get), there is a classic reload.
how can this be fixed?

**Comment by Bythem-la** [comment]
You are asking for the library to stop the normal behavior of all `<form>` in the page, intercept the submit event and make the request with Ajax.

Why don't you just make the Ajax request yourself, instead of using a `<form>`?

**Comment by xavierfoucrier** [comment]
Hi @abramowsergey1992,

As Barba make your site run like a **SPA**, you need to manage form requests by sending them through XHR instead of regular submit, this way you won't notice any browser reload.

If you need further help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
