### ISSUE TITLE
Shopify x Barba JS

### ISSUE THREAD

**Issue by haroldao** [barbajs/barba#670]
Has anyone had success with Barba and Shopify?

**Comment by xavierfoucrier** [comment]
Hi @haroldao,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

> As I know, Shopify x BarbaJS have no problem working together.
