### ISSUE TITLE
Bug using locomotive-scroll, Barba and GSAP

### ISSUE THREAD

**Issue by jeronimus23** [barbajs/barba#671]
Hi, I am creating a personal website and I cannot make it works properly. All three libraries are working but there's a bug when I go from one page to another. After clicking an item in the menu, the page makes the animated transition but then when the other page is loaded the content is not displayed entirely. 

Could you help me to find out how to make it works?

code here:
https://www.hallnatura.com/ex-barba/index.html

**Comment by xavierfoucrier** [comment]
Hello @jeronimus23,

I get a look at your code: you need to "update" locomotive after a page transition.
I guess this is the only thing that is missing :wink: 

Because Locomotive take care of the viewport height for scroll animation, you need to update it in order to compute the new page height. When the `current` barba container will be removed, the `next` page container (most time) will have a different height.

> There is a dedicated section for Locomotive right here:
> https://barba.js.org/docs/advanced/third-party/#Locomotive-scroll

**Comment by jeronimus23** [comment]
Thank you @xavierfoucrier!. I will try to do it following the guidelines.

**Comment by jeronimus23** [comment]
That worked! thanks!
