### ISSUE TITLE
There is an issue when trying to load CDN's when going to a different page

### ISSUE THREAD

**Issue by talmax1124** [barbajs/barba#672]
Hello! I am using this with GSAP for page transitions. But when I have a CDN, it doesn't allow it to remain it's styling. Any fixes.

How it's supposed to look:
<img width="1488" alt="Screen Shot 2022-04-03 at 4 24 35 PM" src="https://user-images.githubusercontent.com/61528430/161447019-ae2c99b8-8ed1-40bd-9216-924b96d049b2.png">

How it looks when navigating back from another page:
<img width="1487" alt="Screen Shot 2022-04-03 at 4 25 15 PM" src="https://user-images.githubusercontent.com/61528430/161447048-96a366ee-6456-4d0f-9998-2112b2207881.png">

**Comment by xavierfoucrier** [comment]
Hi @talmax1124,

This issue is more related to **how your code is running** than Barba v2 issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
