### ISSUE TITLE
Barba wrapper width issue

### ISSUE THREAD

**Issue by jloafs** [barbajs/barba#673]
I have a design that uses 4 absolutely positioned elements pinned to the 4 corners of the screen. 

The problem is that since wrapping the body of the page in a barba wrapper, the elements on the right hand side are overlapping the scrollbar.

Is there a way around this?

**Comment by xavierfoucrier** [comment]
Hi @jloafs,

This issue is more related to **how your code is running** than Barba v2 issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
