### ISSUE TITLE
Barba v1 and tsParticles

### ISSUE THREAD

**Issue by mysteryprod** [barbajs/barba#683]
Hello,

I'm using Barba.js v1 with some particles loaded on the Homepage.
When switching to another page and back to the Homepage the canvas used for particules is empty.

Is there a way to reload the canvas again ?
Thanks

**Comment by xavierfoucrier** [comment]
Hi @mysteryprod,

Unfortunately, Barba v1 is no longer maintained...
You should [**take a look at the v2**](https://barba.js.org/).

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

I am closing the issue.
