### ISSUE TITLE
Barba Locomotive GSAP

### ISSUE THREAD

**Issue by vineeth-22** [barbajs/barba#684]
I'm facing some issues with barba.js
The transition is working fine. The redirect page is taking time to load fully until refresh. Could you anyone help with this?

http://spread.film/test/

**Comment by xavierfoucrier** [comment]
Hi @vineeth-22,

This issue is more related to **how your code is running** than Barba v2 issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
