### ISSUE TITLE
Javascript files do not work after page transition with barba js

### ISSUE THREAD

**Issue by danigrs** [barbajs/barba#699]
Hello guys I know there are a lot of issues where people describe their problem in loading Javascipt files but I spent days figuring out where my mistake is so I would be glad if someone can correct my code:

**JS**:
```

barba.init({
    transitions: [{
      name: 'opacity-transition',
      leave(data) {
        return gsap.to(data.current.container, {
          opacity: 0
        });
      },
      enter(data) {
        return gsap.from(data.next.container, {
          opacity: 0
        });
      }
    }]
  });

// Array with my functions
const functions = [hideMenu, showMenu, reveal, zoomIn, slideLeft, slideRight, 
    toggleDarkMode, registerTouchStartEvent, resetFormsOnUnload];

// disable functions 
function killEvents() {
    functions.forEach((func) => {
        func.disable();
});
}
  
// enable functions
function registerEvents() {
    functions.forEach((func) => {
        func.enable();  
});
}
  
// register events
registerEvents();
  
// kill events before entering 
barba.hooks.beforeEnter(() => {
    killEvents();
});

// activate events after
barba.hooks.after(() => {
    registerEvents();
});

```

I added the CDN link for barba and gsap in my head and the script tag for my js file is above the closing body tag.
like so:

**HTML**:

```
<body>
<main data-barba="wrapper">
<main data-barba="container" data-barba-namespace="home">

<!--Content-->

</main> <!--closing main tag for barba container-->

<script src="script.js" defer></script>

</body>

```

I did this on both html pages but with different content.

Could someone please correct my Code with the following function for the responsive nav bar. I tried different examples mentioned here on github but nothing worked.

**JS**:
```

var navLinks = document.getElementById("navLinks");

    function hideMenu(){
        navLinks.style.right = "-100%";
    }

    function showMenu(){
        navLinks.style.right = "0";
    }
 
```

**Comment by xavierfoucrier** [comment]
Hi @danigrs,

This issue is more related to **how your code is running** than Barba v2 issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support.
Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

ℹ️ Short answers I can give you:
- if the problem is related to loading another JS file after a page transition, you should wait for the [`@barba/head` plugin](https://barba.js.org/docs/plugins/head/) to be released or code your own component
- you got coding issues, your HTML source is bad: two duplicated `main` element, and one of it is not properly closed... you should read/lint/test your code twice before posting here
- for further questions, first read the whole documentation, then if you can't figure out to find the answer, join the community on Slack

**Comment by danigrs** [comment]
Hi @xavierfoucrier,

sorry my fault, my (data-barba="wrapper") is in the body tag, I just pasted it incorrectly here on github. Still thank you for the fast response.
