### ISSUE TITLE
how to create transition sliding up card?

### ISSUE THREAD

**Issue by heyadeivan** [barbajs/barba#719]
How to make a page switch like the following site:
https://www.samuel-medvedowsky.com/

Can i use barbajs + gsap / css transition? 

i found tutorial here : https://ihatetomatoes.net/page-transitions-tutorial-barba-with-css/#how-to-create-cover-transition
but I don't understand how to set up the barba.init.

Thanks

**Comment by xavierfoucrier** [comment]
Hi @heyadeivan,

Thanks for auto-closing your issue 😉 

I just want to highlight that before posting issues to Github, we have a dedicated place for questions not related to Barba "technical issue".

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support.
Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
