### ISSUE TITLE
About `View` transitions API

### ISSUE THREAD

**Issue by xcrap** [barbajs/barba#726]
It's not really an issue; it's more of a question. Now, with the views APIs and such, will this project still proceed, or?

**Comment by xavierfoucrier** [comment]
Hello @xcrap 👋 

Thanks for asking!

As developers, we care about new upcoming technologies, but since this the `View` transitions API is not widely supported at this time, see https://caniuse.com/?search=view%20API, we will keep moving forward on BarbaJS 😎.

There will probably be a time where Barba will become outdated, at that time we will make the necessary decisions.

**Comment by xcrap** [comment]
Thanks a lot for the quick feedback. I'm using Barba.js for many projects, and it's the best transitions library ever. I thought it could even integrate seamlessly with the Views API. Anyway, all the best and thanks.

**Comment by xavierfoucrier** [comment]
Yup @xcrap,

Depending on `View` transitions API support and features, we could of course refactor the library to integrate this.
Let's see what the web's future is going to be ❤️
