### ISSUE TITLE
POST Form transition

### ISSUE THREAD

**Issue by hebergemeweb** [barbajs/barba#727]
Good morning,

I'm discovering Barba little by little and it's great! But how to make Barba work during a POST form submit?

Thanks,

**Comment by xavierfoucrier** [comment]
Hi @hebergemeweb,

This issue is more related to **how your code is running** than Barba v2 issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support.
Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

> Consider using Barba for page transitions, if you want to look at form submit status, you need to use `XMLHttpRequest` or `fetch` APIs.
