### ISSUE TITLE
Cannot find package @barba/barba.umd.js.map@latest

### ISSUE THREAD

**Issue by emirhangungormez** [barbajs/barba#728]
## Prerequisites

"Could not read source map for https://unpkg.com/@barba/core: Unexpected 404 response from https://unpkg.com/@barba/barba.umd.js.map: Cannot find package @barba/barba.umd.js.map@latest"

What should I do in case of this error?

Is my <script> definition wrong? I also uploaded different identification links, but it did not work.

```
<script src="https://unpkg.com/@barba/core"></script>
<script src="https://unpkg.com/@barba/core@2.9.7"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.2.6/gsap.min.js"></script>
<script src="./script.js"></script>
```

I downloaded barba.js to my local but I got the same error, I think I did something wrong. Can you offer me a road map?

I also downloaded a ready-made repo from a barba.js developer. Then the same error is received. I think there was an update to the library and the link changed.

**Comment by xavierfoucrier** [comment]
Hello @emirhangungormez 👋 

The map you are searching is here:
https://unpkg.com/browse/@barba/core@2.9.7/dist/barba.umd.js.map

> You need to specify for which (sub)package you want the source map.

You can see all files here:
https://unpkg.com/browse/@barba/core@2.9.7/dist/

**Comment by emirhangungormez** [comment]
Hi, thank you for the answer. However, I had tried this map before the question. I'm still getting the same error. What could be the reason?

**Comment by xavierfoucrier** [comment]
Hello @emirhangungormez 👋 

This issue is mainly due to **unpkg redirections**.

When you ask unpkg to load `https://unpkg.com/@barba/core` or `https://unpkg.com/@barba/core@2.9.7`, the website redirects you to `https://unpkg.com/@barba/core@2.9.7/dist/barba.umd.js`.

Knowing this, you need to update your html syntax properly:
```html
<script src="https://unpkg.com/@barba/core@2.9.7/dist/barba.umd.js"></script>
```

![image](https://github.com/barbajs/barba/assets/2471223/1ff21138-a714-4504-80a8-5df4955b22f7)

Hope it's clear now 😉
