### ISSUE TITLE
OWL Carousel doesn't work

### ISSUE THREAD

**Issue by SalvoBevilacqua** [barbajs/barba#744]
### What version are you using?

barba js V2

### What package are you using?

@barba/core

### Describe your issue

I use barba to apply transitions, I have several custom scripts that work without any problem, I use GSAP, scroll smother and scrolltrigger in all pages without prob but owl carousel does not initialize. I tried various hooks, but nothing.
thank you
![Screenshot_1](https://github.com/user-attachments/assets/c1dc016d-b76b-4474-b995-ef6a4fdda9cc)
![Screenshot_2](https://github.com/user-attachments/assets/fb06747b-3429-4259-abed-7516971d857e)

**Comment by xavierfoucrier** [comment]
Hi @SalvoBevilacqua,

This issue is more related to **how your code is running** than Barba v2 issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support.
Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
