### ISSUE TITLE
Firefox scroll to top after transition not working

### ISSUE THREAD

**Issue by fweth** [barbajs/barba#751]
### What version are you using?

v2.10.0

### What package are you using?

@barba/core

### Describe your issue

Hi, I noticed that on Firefox, when you add `scrollBehavior: smooth` to the root container, the scrolling to top after a transition sometimes doesn't work.  This can be even seen on your own website (after enabling `scrollBehavior: smooth` via JS) but only on certain routes, when I go to "Basic transitions", then scroll down and then navigate to "Run custom code", it doesn't scroll up.  I had the same issue on another site I'm maintaining.  It seems somehow connected to GSAP, and I'm pretty sure it's a FF bug, but my suggestion, could you maybe open source the Barba.js website?  Then it would be easier to track this down.

**Comment by xavierfoucrier** [comment]
Hi @fweth,

This issue is more related to **how your code is running** than Barba v2 issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support.
Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
